import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/Sidebar";
import Rightsidebar from "@/components/shared/Rightsidebar";

const grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZuAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${grotesk.className} bg-blue-100`}>
        <main className="flex">
          <Sidebar />
          <section className="w-dvw">{children}</section>
          <Rightsidebar />
        </main>
      </body>
    </html>
  );
}
